---
- name: sample book
  hosts: localhost
  gather_facts: false # this is much faster as the host is not queried - but some system variables are now empty
  connection: local # no ssh - just use the host (can be also used in tasks & roles)

# https://docs.ansible.com/ansible/latest/collections/ansible/utils/index.html

# this will also needs "netaddr" in the python requirements.txt file
  tasks:
    - name: Check if given string is a MAC address
      debug:
        msg: "{{ '1a:2b:3c:4d:5e:6f' | ansible.utils.hwaddr }}"