---
- name: sample book
  hosts: testvm

# https://docs.ansible.com/ansible/latest/collections/ansible/utils/index.html

# this will also needs "netaddr" in the python requirements.txt file
  tasks:
    - name: Check if given string is a MAC address
      debug:
        msg: "{{ '1a:2b:3c:4d:5e:6f' | ansible.utils.hwaddr }}"